name: Danger Checks

# This will cancel any in progress workflows for the same PR, if
# multiple pushes happen in quick succession.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on: pull_request

jobs:
  danger:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # required for Danger to post comments
      issues: write # required for Danger to post comments
      contents: read
      packages: write
      checks: write        # Necessary to write reports
      actions: write       # Necessary to cancel workflow executions
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/workflow_setup

#      - name: Dependency Updates
#        run: ./gradlew dependencyUpdates

      - name: Danger Checks
        uses: danger/kotlin@1.3.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}